# Exercises (Optional)

These exercises are not required to complete however are good to do for practice. (Not to be submitted on git)

These exercises are a mix of Python and pandas/EDA practice. Most should be no more than a few lines of code! 

In [37]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

# get a list containing the last 3 elements of a

b=a[3:]
print(b)

# reverse the list
rev=a[::-1]
print(rev)

# get a list where each entry in a is squared (so the new list is [1, 4, 9, 16, 25, 36])
j=[]
for x in a:
    x=x*x
    j.append(x)
print(j)

[4, 5, 6]
[6, 5, 4, 3, 2, 1]
[1, 4, 9, 16, 25, 36]


In [38]:
# create a numpy array from this list
b = [0,45,34,2,1,-59] # change this
import numpy as np;
b=np.array(b)

In [39]:
# find the mean of b
np.mean(b)

3.8333333333333335

In [40]:
# get a list where each entry in b is squared (so the new numpy array is [1, 4, 9, 16, 25, 36])
# use a different (numpy-specific) approach

b=b**2
print(b)


[   0 2025 1156    4    1 3481]


In [55]:
# change b from a length-6 list to a 2x3 matrix
j=b.reshape(2,3)
print(j)

[[   0 2025 1156]
 [   4    1 3481]]


In [57]:
# find the mean value of each row
print(j[0].mean())
print(j[1].mean())

1060.3333333333333
1162.0


In [163]:
# find the mean value of each column

np.mean(j, axis=0)

array([2.0000e+00, 1.0130e+03, 2.3185e+03])

In [164]:
# find the third column of b
print(j[:][2])

##????? Google this!

IndexError: index 2 is out of bounds for axis 0 with size 2

In [162]:
# load in the "starbucks.csv" dataset
import pandas as pd
df =  pd.read_csv("../data/starbucks.csv")
df.to_numpy()
df=df.set_index('beverage_category')
##df.columns = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
##print(df[1])
print(df.index.unique().size)
df.head()
#df["beverage"]

9


beverage_category
coffee                                                   brewed coffee
coffee                                                   brewed coffee
coffee                                                   brewed coffee
coffee                                                   brewed coffee
classic espresso drinks                                     caff latte
                                               ...                    
frappuccino blended crme    strawberries  crme (without whipped cream)
frappuccino blended crme          vanilla bean (without whipped cream)
frappuccino blended crme          vanilla bean (without whipped cream)
frappuccino blended crme          vanilla bean (without whipped cream)
frappuccino blended crme          vanilla bean (without whipped cream)
Name: beverage, Length: 242, dtype: object

In [116]:
# this is nutritional info for starbucks items
# let's see if we can answer some questions

# what is the average # calories across all items?
print(df.calories.mean())


193.87190082644628


In [122]:
# how many different categories of beverages are there?
df.index.unique().size

9

In [189]:
# what is the average # calories for each beverage category?

indices = df.index.unique()
#print(df.loc["coffee"])
for i in indices:
    newDf=df.loc[i]
    print(newDf.calories.mean())

4.25
140.17241379310346
250.0
177.30769230769232
114.44444444444444
282.22222222222223
276.94444444444446
162.5
233.07692307692307


In [ ]:
# what beverage preparation includes the most sugar on average?


In [ ]:
# what is the average % daily value calcium content for each beverage?


In [ ]:
# It's bulking season. What drink should Naitian get so that he maximizes protein but minimizes calories?
# (you can use more than one line for this one)
# there are multiple valid approaches you can take for this (with different answers)
# I know that you want more calories for bulking season but whatever this is MDST, not Michigan Muscle Club okay


In [ ]:
# plot the distribution of the number of calories in drinks using matplotlib


In [ ]:
# plot the same distribution using seaborn. what about a density plot instead?


In [ ]:
# plot calories against total fat using seaborn


In [ ]:
# plot the distribution of calories in Short, Tall, Grande, and Venti drinks
# (you can use multiple lines for this)
# twist: you should also include the Nonfat Milk drinks that also have an associated size.

# you can decide how you want to visualize this. Colors? Small multiples? Density vs histogram?
# the starbucks is your oyster.
